### ISSUE TITLE
ICBM issues

### ISSUE THREAD

**Issue by Nbgreen** [Aquerr/EagleFactionsAPI#1]
when 
allow-explosions-by-other-players-in-claims=true
is set to true
 ICBM explosives don't destroy the blocks. it does but the block stays which dupes the blocks and if the block has an inventory it is duped as well

**Comment by Aquerr** [comment]
Issue related to implementation of Eagle Factions API. I am closing this as EagleFactionsAPI has nothing to do with it and we have possibly fixed some things already since 29 September.
